Update GitHub Actions workflow and frontend components for improved build process and environment variable handling
- Renamed the build job in the GitHub Actions workflow from 'build-and-push-image' to 'build-and-push-backend' for clarity.
- Added a new job 'build-and-push-frontend' to handle the frontend Docker image build, including checks for required secrets.
- Updated frontend components to ensure the Stripe publishable key is loaded correctly using template literals.
- Enhanced the overall structure of the workflow for better maintainability and clarity.

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -9,8 +9,9 @@ permissions:
   packages: write
 
 jobs:
-  build-and-push-image:
+  build-and-push-backend:
     runs-on: ubuntu-latest
+    environment: production
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -41,6 +42,40 @@ jobs:
           cache-from: type=gha
           cache-to: type=gha,mode=max
 
+  build-and-push-frontend:
+    runs-on: ubuntu-latest
+    environment: production
+    steps:
+      - name: Check required secrets
+        run: |
+          if [ -z "${{ secrets.REACT_APP_MAILERLITE_API_KEY }}" ]; then
+            echo "Error: REACT_APP_MAILERLITE_API_KEY is not set"
+            exit 1
+          fi
+          if [ -z "${{ secrets.REACT_APP_STRIPE_PUBLISHABLE_KEY }}" ]; then
+            echo "Error: REACT_APP_STRIPE_PUBLISHABLE_KEY is not set"
+            exit 1
+          fi
+          
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        
+      - name: Set short git commit SHA
+        id: vars
+        run: |
+          calculatedSha=$(git rev-parse --short ${{ github.sha }})
+          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
+          
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+          
+      - name: Log in to the Container registry
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+          
       - name: Build and push frontend Docker image
         uses: docker/build-push-action@v5
         with:
